from django.contrib import admin

from cl2csv.options import ExportModelAdmin

from support.models import (
    AnnualSupporters, AutoGeneratedEmail, CommunityCampaign, 
    MembershipBenefit, MembershipLevel, NewDonation
)


class NewDonationAdmin(ExportModelAdmin):
    raw_id_fields = ('user',)
    search_fields = ('contact_email', 'first_name', 'last_name', 'user__username', 'user__email', 'gift')
    list_display = ('created', 'amount', 'payment_method', 'first_name', 'last_name', 'contact_email', 'gift')
    list_filter = ('payment_method', 'created')
    date_hierarchy = 'created'

class MembershipLevelAdmin(admin.ModelAdmin):
    filter_horizontal = ('benefits',)

class CampaignAdmin(ExportModelAdmin):
	readonly_fields = ('amount_raised',)
	list_display = ('year', 'days_left', 'amount_raised', 'amount_goal', 'percent_raised', 'is_active')

admin.site.register(AnnualSupporters)
admin.site.register(AutoGeneratedEmail)
admin.site.register(CommunityCampaign, CampaignAdmin)
admin.site.register(MembershipBenefit)
admin.site.register(MembershipLevel, MembershipLevelAdmin)
admin.site.register(NewDonation, NewDonationAdmin)
